# Generated by Django 3.2.4 on 2021-06-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='ketwords',
            new_name='keywords',
        ),
    ]
