# Generated by Django 3.2.4 on 2021-07-01 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='news',
            name='prince',
        ),
    ]
